### ISSUE TITLE
Running the app

### ISSUE THREAD

**Issue by hasit** [citwild/wfe#1]
Hello @cafarm,

Could you please post instructions to run the server?

**Comment by cafarm** [comment]
It doesn't do much at the moment. I'm trying to get all the tiers in place before I build them out so that I understand how the full stack is going to work.

That said, if you're still interested in playing with it there are two approaches:

**1. Play with the deployed app on AWS**
The app is deployed to AWS every time a push occurs to the master branch. The url is https://wfe-dev.us-west-2.elasticbeanstalk.com. Note that we're using a self-signed cert so the browser will warn you about the cert. If you accept the cert you'll see "Not yet implemented". That's about the extent of the functionality at the moment...

**2. Run the server locally**
If you want to run the server locally, you need to run a MongoDB server before you start the WFE server. A nice way to run MongoDB is in a docker container. 

Here are the steps:
1. Download and install [docker](https://www.docker.com)
2. `docker pull mvertes/alpine-mongo`
3. `docker run -d --name mongo -p 27017:27017 mvertes/alpine-mongo`
4. `go get -u -v github.com/citwild/wfe/cmd/wfe`
5. `wfe serve`
6. Go to [localhost:8080](http://localhost:8080) in your browser and you'll see "Not yet implemented"

**Comment by hasit** [comment]
Mind updating the README with this information?

**Comment by cafarm** [comment]
Considering it... There's going to be a bunch of wfe subcommands for managing the db and other things ("serve" is just one of many) so I'm not sure I want to detail them all in the README. I'd rather "wfe -h" be more informational.

**Comment by hasit** [comment]
It's almost always better to have it on README. You are using codegangsta/cli, right?

**Comment by cafarm** [comment]
Probably true. I just want to avoid repeating between the readme and code because they're bound to get out of sync. It might make sense when we nail down the subcommands more. Using sourcegraph's go-flags.
